#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NavigationDrawer.Resource", IsApplication=true)]

namespace NavigationDrawer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int drawer_sections = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int background_color = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int drawer_icon = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int drawer_shadow = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int drawer_background = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int drawer_item_text_color = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int light_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060001
			public const int drawer_item_padding = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int drawer_width = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drawer_shadow_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawer_shadow_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_drawer_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_drawer_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090002
			public const int content_frame = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int drawer_layout = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int left_drawer = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int textView1 = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int fragment1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int item_menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int drawer_close = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int drawer_open = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int fragment1 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int fragment2 = 2131165187;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int BaseTheme = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int BaseThemeLight = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int BaseThemeLightDarkActionBar = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int Theme = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int ThemeLight = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int ThemeLightDarkActionBar = 2131230725;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
